name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install antlr4-tools

    - name: Run setup script
      run: |
        chmod +x ufc/setup.sh
        ./ufc/setup.sh

    - name: Check formatting with Black
      run: |
        black --check .

    - name: Run tests
      run: |
        pytest tests/
